- name: Check and create SaveAbort.yml
  hosts: server1
  tasks:
    - block:
      - name: Check if exists
        stat: 
          path: /var/tmp/saveabort.yml
        register: fileexists

      - name: come out of the program if file exists
        meta: end_play
        when: fileexists.stat.exists == true
      become: true

    - name: create file
      file: 
        path: /var/tmp/saveabort.yml 
        state: touch


        