- name: Manage MySQL
  hosts: amazon-linux
  roles:
    - role: manage_my_sql_role
  tasks:
    - 

    

    

    

    - name: Start MySQL Server and enable it
      service: name=mysqld state=started enabled=yes